### ISSUE TITLE
Database upgrade fails with Could not connect to MySQL server: SQL error when doing 'Connection.setAutoCommit(false)'

### ISSUE THREAD

**Issue by dtretyakov** [dtretyakov/teamcity-azure-template#6]
During database converters execution upgrade may fails with the following exception:

```java
Feb 12 11:26:05 teamcity docker[2043]: [2019-02-12 11:26:05,092]  ERROR -  jetbrains.buildServer.STARTUP - Exception UnknownUpgradeError in stage UPGRADE: Upgrading error: Could not connect to MySQL server: SQL error when doing 'Connection.setAutoCommit(false)': com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 936,932 milliseconds ago.  The last packet sent successfully to the server was 936,935 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem. Caused by: java.net.SocketException: Connection reset
Feb 12 11:26:05 teamcity docker[2043]: jetbrains.buildServer.maintenance.exceptions.UnknownUpgradeError: Upgrading error: Could not connect to MySQL server: SQL error when doing 'Connection.setAutoCommit(false)': com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 936,932 milliseconds ago.  The last packet sent successfully to the server was 936,935 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem. Caused by: java.net.SocketException: Connection reset
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor.doUpgrade(StartupProcessor.java:1000)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor.access$1400(StartupProcessor.java:1039)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor$3.call(StartupProcessor.java:13)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:91)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStage(StartupProcessor.java:568)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor.processConcreteStageSafe(StartupProcessor.java:569)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor.processTeamCityLifecycle(StartupProcessor.java:769)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor.access$000(StartupProcessor.java:869)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor$1.run(StartupProcessor.java:3)
Feb 12 11:26:05 teamcity docker[2043]:         at java.lang.Thread.run(Thread.java:748)
Feb 12 11:26:05 teamcity docker[2043]: Caused by: jetbrains.buildServer.serverSide.db.DatabaseIsNotReachableException: Could not connect to MySQL server: SQL error when doing 'Connection.setAutoCommit(false)': com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 936,932 milliseconds ago.  The last packet sent successfully to the server was 936,935 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem. Caused by: java.net.SocketException: Connection reset
Feb 12 11:26:05 teamcity docker[2043]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Feb 12 11:26:05 teamcity docker[2043]:         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Feb 12 11:26:05 teamcity docker[2043]:         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Feb 12 11:26:05 teamcity docker[2043]:         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Feb 12 11:26:05 teamcity docker[2043]:         at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
Feb 12 11:26:05 teamcity docker[2043]:         at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
Feb 12 11:26:05 teamcity docker[2043]:         at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3746)
Feb 12 11:26:05 teamcity docker[2043]:         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509)
Feb 12 11:26:05 teamcity docker[2043]:         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
Feb 12 11:26:05 teamcity docker[2043]:         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
Feb 12 11:26:05 teamcity docker[2043]:         at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4811)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.serverSide.db.DBFunctions.setAutoCommit(DBFunctions.java:1088)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.serverSide.versioning.ConvertPerformer.runConverter(ConvertPerformer.java:108)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.serverSide.versioning.ConvertPerformer.runConverters(ConvertPerformer.java:87)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.serverSide.versioning.VersionManager.upgradeIt(VersionManager.java:381)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor$UpgradePerformer.doUpgrade(StartupProcessor.java:3)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor.lambda$doUpgrade$7(StartupProcessor.java:882)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.serverSide.db.TeamCityDatabaseManager$3.run(TeamCityDatabaseManager.java:942)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.serverSide.db.TeamCityDatabaseManager$3.run(TeamCityDatabaseManager.java:937)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.serverSide.db.TeamCityDatabaseManager.withMaintenanceDBF(TeamCityDatabaseManager.java:921)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.serverSide.db.TeamCityDatabaseManager.withMaintenanceDBF(TeamCityDatabaseManager.java:937)
Feb 12 11:26:05 teamcity docker[2043]:         at jetbrains.buildServer.maintenance.StartupProcessor.doUpgrade(StartupProcessor.java:554)
Feb 12 11:26:05 teamcity docker[2043]:         ... 9 more
Feb 12 11:26:05 teamcity docker[2043]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 936,932 milliseconds ago.  The last packet sent successfully to the server was 936,935 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
Feb 12 11:26:05 teamcity docker[2043]:         ... 31 more
Feb 12 11:26:05 teamcity docker[2043]: Caused by: java.net.SocketException: Connection reset
Feb 12 11:26:05 teamcity docker[2043]:         at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
Feb 12 11:26:05 teamcity docker[2043]:         at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
Feb 12 11:26:05 teamcity docker[2043]:         at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
Feb 12 11:26:05 teamcity docker[2043]:         at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
Feb 12 11:26:05 teamcity docker[2043]:         at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3728)
Feb 12 11:26:05 teamcity docker[2043]:         ... 24 more

```

**Comment by dtretyakov** [comment]
The problem with autocommit was fixed in [MySQL JDBC driver 5.1.46](https://dev.mysql.com/doc/relnotes/connector-j/5.1/en/news-5-1-46.html).
